seed: 18
dataset_path: ./SRW/sample_imgs
limit: 500
output_path: ./SRW/results/imgs

path: ./SRW/results/ModelB
  
pgd:
  attack: false
  epsilon: [0.03,0.04]
  alpha: [0.007,0.01]
  num_iter: [50,100]

